name: GitHub actions con integracion de agave-cli
run-name: GitHub actions con integracion de agave-cli
on: [push]
jobs:
    go: 
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.16.1' # The Go version to download (if necessary) and use.
      - name: Github configuraion
        run: |
          git config --global url."https://${{ secrets.GIT_TOKEN }}:x-oauth-basic@github.com/99minutos".insteadOf "https://github.com/99minutos"
          echo machine github.com login cchavezmx99 password ${{ secrets.GIT_TOKEN }} >> ~/.netrc
          go install github.com/99minutos/agave-cli@latest