name: GitHub actions con integracion de agave-cli
run-name: GitHub actions con integracion de agave-cli
on: [push]
jobs:
    go: 
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.16.1' # The Go version to download (if necessary) and use.
      - name: Github configuraion
        run: |
          go version
          export GIT_TOKEN=${{ secrets.GIT_TOKEN }}
          echo machine github.com login cchavezmx99 password $GIT_TOKEN >> ~/.netrc
          go install github.com/99minutos/agave-cli@latest
      