name: GitHub actions con integracion de agave-cli
run-name: GitHub actions con integracion de agave-cli
on: [push]
jobs:
    go: 
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.16.1' # The Go version to download (if necessary) and use.
      - name: Github configuraion
        run: |
          go version
          export GIT_TOKEN=${{ secrets.GIT_TOKEN }}
          git config --global user.name "cchavezmx99"
          git config --global user.email "carlos.chavez@99minutos.com"
          git config --global url."https://${GIT_TOKEN}:x-oauth-basic@github.com/99minutos".insteadOf "https://github.com/99minutos"
      - name: install agave-cli
        uses: actions/checkout@v2
        with:
          repository: 99minutos/agave-cli
          ref: v2.2.0
          path: agave-cli
          token: ${{ secrets.GITHUB_TOKEN }}
          run: |
            cd agave-cli
            go install